### ISSUE TITLE
User can create a new task

### ISSUE THREAD

**Issue by NickANewton** [NickANewton/react-todo#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a new task
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can type a new task into the input and submit it by pressing the add button

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="397" alt="Screen Shot 2022-08-13 at 11 45 55 AM" src="https://user-images.githubusercontent.com/99566488/184506863-449fba46-3e06-4c3e-9d48-ebdb8bb24f6a.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Create layout for app name, input and button
- [x] Ensure the styling looks good on mobile and desktop views
- [x] On submit, update the state to and unshift the new task
- [x] Ensure the app works as intended in a private browsing tab
- [x] Remove any unnecessary styling 
- [x] Fix all errors
