### ISSUE TITLE
User can view tasks

### ISSUE THREAD

**Issue by NickANewton** [NickANewton/react-todo#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view tasks
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the app loads, the user can view each of their tasks, as well  as when a new task is entered. The newest task will appear at the top.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="397" alt="Screen Shot 2022-08-16 at 10 02 25 AM" src="https://user-images.githubusercontent.com/99566488/184937168-aa36bbc1-3eba-44a7-9835-20ddc2ac3a34.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Create layout for the tasks
- [x] Ensure the styling looks good on mobile and desktop views
- [x] Use the map method to render each task store in state
- [x] Ensure the app works as intended in a private browsing tab
- [x] Remove any unnecessary styling 
- [x] Fix all errors
