### ISSUE TITLE
User can check off task

### ISSUE THREAD

**Issue by NickANewton** [NickANewton/react-todo#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can check off task
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can mark tasks as done. When the task is clicked, the white circle icon will change to a checked icon and the text will have a strike through.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="397" alt="Screen Shot 2022-08-16 at 12 50 41 PM" src="https://user-images.githubusercontent.com/99566488/184972258-35cf24d8-63c3-4dac-8880-5336f3f6f7fd.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Add plain circle icon to each task
- [x] when the task is clicked, render a checked icon 
- [x] when the task is clicked strike through text
- [x] reverse the check and strike when clicked again
- [x] Ensure the app works as intended in a private browsing tab
- [x] Remove any unnecessary styling 
- [x] Fix all errors
