### ISSUE TITLE
User can delete task

### ISSUE THREAD

**Issue by NickANewton** [NickANewton/react-todo#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete task
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click a trash icon to remove the task from the task list

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
<img width="397" alt="Screen Shot 2022-08-16 at 3 40 44 PM" src="https://user-images.githubusercontent.com/99566488/184997795-1858732a-be0a-4f34-b21c-d901750a25c2.png">
<img width="397" alt="Screen Shot 2022-08-16 at 3 40 58 PM" src="https://user-images.githubusercontent.com/99566488/184997807-2f91db22-93a2-4804-b8d2-8bc2f2afc75a.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Add trash icon to each task
- [x] Create a handleDelete function to remove the task from the list when the icon is clicked
- [x] Ensure the app works as intended in a private browsing tab
- [x] Remove any unnecessary styling 
- [x] Fix all errors
